"""Count-world (motivic) computation, all in the variable w = q^{-1}.

Rigorous foundation (proved by F_q point count, stratifying by the subspace
generated by the framing vector):

    q^d T_d = sum_{e+f=d} h_e q^{(m-1)ef} T_f,        (*)
    T_k = q^{mk^2}/#GL_k(F_q),   h_d = #Hilb_{d,1}^{(m)}(F_q).

Substituting q = 1/w and gauging (t_k := w^{(m-1)k^2} T_k(1/w) = 1/(w;w)_k,
eta_e := w^{(m-1)e^2+e} h_e(1/w)) turns (*) into the gauge product identity

    t = eta (*) t',    t'_f := w^f t_f,
    (gauge product at degrees (e,f) carries shift w^{(m-1)ef}).

True-series form: TT(x) = HH(x) * TT(w x), so HH(x) = TT(x)/TT(w x).

DT invariants (count normalization): TT(x) = Exp( sum_d baromega_d(w) x^d ),
Omega^c_d(w) := (1-w) * baromega_d(w).  Then

    PLog(HH)_d = (1 - w^d) baromega_d = Omega^c_d(w) * [d]_w.       (**)

This file:
 1. computes Omega^c_d(w) from t via PLog (exact),
 2. compares Omega^c_d(w) with the cohomological Omega~_d(z) data (monomial match),
 3. computes eta_d via the ratio identity and compares with q-Fuss-Catalan,
 4. extracts G_n := n [x^n] log(eta-series) and pattern-matches q-binomials,
 5. verifies (**) exactly: (1/d) sum_{r|d} mu(r) psi_r(G_{d/r}) == Omega^c_d [d]_w.
"""

import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from dt_core import (moebius, divisors, ptrunc, pmul, pshift, pgeom, ppsi,
                     pdiv_exact, pitems, DATA_DIR)
from flint import fmpz_poly
from refined_framed import qFC, ptrim


def t_coeff(d, cap):
    """t_d = 1/(w;w)_d as truncated series."""
    c = fmpz_poly([1])
    for j in range(1, d + 1):
        c = pgeom(c, j, cap)
    return c


def gauge_series_ops(F, D, cap, s):
    """Inverse G of F and H_d = d [x^d] log F, for a series whose x^d
    coefficient is gauged by w^{s d^2 (+ linear)}: product of x-degrees (j,k)
    carries shift w^{2 s j k}."""
    G = [None] * (D + 1)
    G[0] = fmpz_poly([1])
    for d in range(1, D + 1):
        acc = fmpz_poly([0])
        for j in range(1, d + 1):
            t = pmul(F[j], G[d - j], cap)
            acc = acc + pshift(t, 2 * s * j * (d - j), cap)
        G[d] = fmpz_poly([0]) - acc
    H = [None] * (D + 1)
    for d in range(1, D + 1):
        acc = fmpz_poly([0])
        for j in range(1, d + 1):
            t = pmul(F[j] * fmpz_poly([j]), G[d - j], cap)
            acc = acc + pshift(t, 2 * s * j * (d - j), cap)
        H[d] = acc
    return G, H


def omega_count(m, D, cap):
    """Omega^c_d(w) via PLog of t-series (gauge s=m-1).  Gauged output:
    entry d is w^{(m-1)d^2} * (true Laurent), a polynomial; we return items
    with TRUE exponents (subtracting the gauge)."""
    s = m - 1
    F = [t_coeff(d, cap) for d in range(D + 1)]
    _, H = gauge_series_ops(F, D, cap, s)
    one_minus_w = fmpz_poly([1, -1])
    out = {}
    for d in range(1, D + 1):
        S = fmpz_poly([0])
        for r in divisors(d):
            mu = moebius(r)
            if mu == 0:
                continue
            e = d // r
            t = ppsi(H[e], r, cap)
            t = pshift(t, s * r * (r - 1) * e * e, cap)
            S = S + t * fmpz_poly([mu])
        barom = pdiv_exact(S, d)
        Om = ptrunc(one_minus_w * barom, cap - 16)
        base = s * d * d
        out[d] = [(i - base, int(Om[i])) for i in range(Om.degree() + 1) if int(Om[i])]
    return out


def eta_series(m, D, cap):
    """eta_d = w^{(m-1)e^2+e} h_e(1/w) via triangular solve of the exact
    counting identity  t_d = sum_{e+f=d} eta_e w^{(m-1)ef + f} t_f."""
    s = m - 1
    t = [t_coeff(d, cap) for d in range(D + 1)]
    eta = [None] * (D + 1)
    eta[0] = fmpz_poly([1])
    for d in range(1, D + 1):
        acc = fmpz_poly([0])
        for e in range(0, d):
            f = d - e
            term = pmul(eta[e], t[f], cap)
            acc = acc + pshift(term, s * e * f + f, cap)
        eta[d] = t[d] - acc
    return eta


def load_omega_z(m):
    with open(os.path.join(DATA_DIR, f"omega_m{m}.json")) as f:
        raw = json.load(f)
    return {int(d): [(e, c) for e, c in items] for d, items in raw.items()}


def monomial_match(itemsA, itemsB_scaled):
    """itemsA, itemsB as (exp, coeff) lists; check A == +- shift of B."""
    if len(itemsA) != len(itemsB_scaled):
        return None
    if not itemsA:
        return (1, 0)
    sh = itemsA[0][0] - itemsB_scaled[0][0]
    sg = None
    for (ea, ca), (eb, cb) in zip(itemsA, itemsB_scaled):
        if ea - eb != sh:
            return None
        r = 1 if ca == cb else (-1 if ca == -cb else None)
        if r is None:
            return None
        if sg is None:
            sg = r
        elif sg != r:
            return None
    return (sg, sh)


def main():
    for m in (2, 3, 4):
        print("=" * 76)
        print(f"m = {m}")
        D = 10
        cap = (m - 1) * D * D + 3 * D + 60
        # --- 1,2: Omega^c vs Omega~ ---
        Oc = omega_count(m, D, cap)
        Oz = load_omega_z(m)
        allmatch = True
        for d in range(1, D + 1):
            # compare in doubled-w-exponent units: A2 exps = 2*e_w;
            # Omega~ in z: q = z^2, w = q^{-1}: try both orientations.
            A2 = sorted([(2 * e, c) for e, c in Oc[d]])
            B_fwd = sorted([(e, c) for e, c in Oz[d]])
            B_rev = sorted([(-e, c) for e, c in Oz[d]])
            r = monomial_match(A2, B_rev) or monomial_match(A2, B_fwd)
            if r is None:
                allmatch = False
                print(f"  d={d}: Omega^c vs Omega~ NO simple monomial match")
                print(f"     Omega^c: {Oc[d][:8]}")
                print(f"     Omega~ : {Oz[d][:8]}")
            else:
                if d <= 4:
                    print(f"  d={d}: Omega^c matches Omega~ (sign {r[0]:+d}, "
                          f"2w-shift {r[1]})  OK")
        print(f"  Omega^c <-> Omega~ all matched: {allmatch}")
        # --- 3: eta vs qFC ---
        eta = eta_series(m, D, cap)
        qfc = [qFC(m, d) for d in range(D + 1)]
        for d in range(1, min(D, 7) + 1):
            A = pitems(eta[d])
            B = [(i, c) for i, c in enumerate(qfc[d]) if c]
            Brev = [(-i, c) for i, c in reversed(B)]
            r1 = monomial_match(A, B)
            r2 = monomial_match(A, sorted(Brev))
            print(f"  d={d}: eta vs qFC: direct={r1} reversed={r2}"
                  f"   (eta has {len(A)} terms, qFC {len(B)})")
        # --- 4: G_n from eta-series (gauge s=m-1) ---
        _, Geta = gauge_series_ops(eta, D, cap, m - 1)
        print("  G_n := n [x^n] log(eta-series), low terms:")
        for n in range(1, min(D, 6) + 1):
            print(f"    G_{n} = {pitems(ptrunc(Geta[n], 40))[:14]}")
        # --- 5: verify the diagonal identity (**) ---
        ok_all = True
        for d in range(1, D + 1):
            S = fmpz_poly([0])
            for r in divisors(d):
                mu = moebius(r)
                if mu == 0:
                    continue
                e = d // r
                t = ppsi(Geta[e], r, cap)
                t = pshift(t, (m - 1) * r * (r - 1) * e * e, cap)
                S = S + t * fmpz_poly([mu])
            # S should equal d * Omega^c_d(w) * [d]_w  (gauged by w^{(m-1)d^2})
            base = (m - 1) * d * d
            lhs = pitems(ptrunc(S, cap - 20))
            qd = fmpz_poly([1] * d)  # [d]_w
            rhs_poly = fmpz_poly([0])
            for e, c in Oc[d]:
                rhs_poly = rhs_poly + pshift(qd * fmpz_poly([c]), e + base, cap)
            rhs_poly = rhs_poly * fmpz_poly([d])
            rhs = pitems(ptrunc(rhs_poly, cap - 20))
            if lhs != rhs:
                ok_all = False
                print(f"  d={d}: identity (**) FAILS")
                print(f"    lhs: {lhs[:10]}")
                print(f"    rhs: {rhs[:10]}")
        print(f"  identity (**) sum mu psi G = d*Omega^c*[d]_w verified: {ok_all}")


if __name__ == "__main__":
    main()
